// <auto-generated />
using System;
using BD_KURSACH.DB_Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BD_KURSACH.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20241210161552_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BD_KURSACH.Models.DET", b =>
                {
                    b.Property<Guid>("KOD_DET")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DET_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DET_Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DET_Вид")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("KOD_SE")
                        .HasColumnType("char(36)");

                    b.Property<int>("S1")
                        .HasColumnType("int");

                    b.HasKey("KOD_DET");

                    b.HasIndex("KOD_SE")
                        .IsUnique();

                    b.ToTable("Detal");
                });

            modelBuilder.Entity("BD_KURSACH.Models.SE", b =>
                {
                    b.Property<Guid>("KOD_SE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("C1")
                        .HasColumnType("double");

                    b.Property<double>("C2")
                        .HasColumnType("double");

                    b.Property<double>("C3")
                        .HasColumnType("double");

                    b.Property<double>("F")
                        .HasColumnType("double");

                    b.Property<Guid>("KOD_UZLA")
                        .HasColumnType("char(36)");

                    b.Property<int>("NP")
                        .HasColumnType("int");

                    b.Property<int>("Razn")
                        .HasColumnType("int");

                    b.Property<string>("SE_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SE_Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SE_Вид")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TN")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("V")
                        .HasColumnType("int");

                    b.Property<int>("Z")
                        .HasColumnType("int");

                    b.Property<int>("Zmax")
                        .HasColumnType("int");

                    b.Property<int>("α1")
                        .HasColumnType("int");

                    b.Property<double>("σ0")
                        .HasColumnType("double");

                    b.Property<double>("σF")
                        .HasColumnType("double");

                    b.Property<double>("σF0")
                        .HasColumnType("double");

                    b.HasKey("KOD_SE");

                    b.HasIndex("KOD_UZLA");

                    b.ToTable("SE");
                });

            modelBuilder.Entity("BD_KURSACH.Models.UZEL", b =>
                {
                    b.Property<Guid>("KOD_UZ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("UZ_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("KOD_UZ");

                    b.ToTable("Uzel");
                });

            modelBuilder.Entity("BD_KURSACH.Models.DET", b =>
                {
                    b.HasOne("BD_KURSACH.Models.SE", "ses")
                        .WithOne("detal")
                        .HasForeignKey("BD_KURSACH.Models.DET", "KOD_SE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ses");
                });

            modelBuilder.Entity("BD_KURSACH.Models.SE", b =>
                {
                    b.HasOne("BD_KURSACH.Models.UZEL", "uzel")
                        .WithMany("ses")
                        .HasForeignKey("KOD_UZLA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("uzel");
                });

            modelBuilder.Entity("BD_KURSACH.Models.SE", b =>
                {
                    b.Navigation("detal")
                        .IsRequired();
                });

            modelBuilder.Entity("BD_KURSACH.Models.UZEL", b =>
                {
                    b.Navigation("ses");
                });
#pragma warning restore 612, 618
        }
    }
}
